import java.util.Scanner;
import java.util.Arrays;

public class BinarySearch {

    // Method to perform Binary Search
        public static int binarySearch(int[] arr, int target) {
                int left = 0;
                        int right = arr.length - 1;

                                while (left <= right) {
                                            int mid = left + (right - left) / 2;

                                                        // Check if target is present at mid
                                                                    if (arr[mid] == target) {
                                                                                    return mid; // Target found, return index
                                                                                                }

                                                                                                            // If target is greater, ignore left half
                                                                                                                        if (arr[mid] < target) {
                                                                                                                                        left = mid + 1;
                                                                                                                                                    } else {
                                                                                                                                                                    // If target is smaller, ignore right half
                                                                                                                                                                                    right = mid - 1;
                                                                                                                                                                                                }
                                                                                                                                                                                                        }

                                                                                                                                                                                                                return -1; // Target not found
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        // Main method to test Binary Search
                                                                                                                                                                                                                            public static void main(String[] args) {
                                                                                                                                                                                                                                    Scanner scanner = new Scanner(System.in);

                                                                                                                                                                                                                                            // Input the size of the array
                                                                                                                                                                                                                                                    System.out.print("Enter the number of elements: ");
                                                                                                                                                                                                                                                            int n = scanner.nextInt();
                                                                                                                                                                                                                                                                    int[] arr = new int[n];

                                                                                                                                                                                                                                                                            // Input the elements of the array
                                                                                                                                                                                                                                                                                    System.out.println("Enter the elements (in any order):");
                                                                                                                                                                                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                        arr[i] = scanner.nextInt();
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                        // Sort the array as Binary Search requires a sorted array
                                                                                                                                                                                                                                                                                                                                Arrays.sort(arr);

                                                                                                                                                                                                                                                                                                                                        // Display the sorted array
                                                                                                                                                                                                                                                                                                                                                System.out.println("Sorted Array:");
                                                                                                                                                                                                                                                                                                                                                        for (int num : arr) {
                                                                                                                                                                                                                                                                                                                                                                    System.out.print(num + " ");
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    System.out.println();

                                                                                                                                                                                                                                                                                                                                                                                            // Input the target element to search for
                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Enter the element to search: ");
                                                                                                                                                                                                                                                                                                                                                                                                            int target = scanner.nextInt();

                                                                                                                                                                                                                                                                                                                                                                                                                    // Perform Binary Search
                                                                                                                                                                                                                                                                                                                                                                                                                            int result = binarySearch(arr, target);

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Display the result
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (result != -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Element found at index: " + result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Element not found in the array.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                