import java.util.Scanner;

public class BubbleSort { 
    // Method to perform Bubble Sort
        public static void bubbleSort(int[] arr) {
                int n = arr.length;
                        boolean swapped;

                                // Outer loop for each pass
                                        for (int i = 0; i < n - 1; i++) {
                                                    swapped = false; // Reset the swapped flag for each pass

                                                                // Inner loop for comparisons
                                                                            for (int j = 0; j < n - i - 1; j++) {
                                                                                            // Swap if elements are in the wrong order
                                                                                                            if (arr[j] > arr[j + 1]) {
                                                                                                                                // Swap arr[j] and arr[j + 1]
                                                                                                                                                    int temp = arr[j];
                                                                                                                                                                        arr[j] = arr[j + 1];
                                                                                                                                                                                            arr[j + 1] = temp;

                                                                                                                                                                                                                swapped = true; // Mark that a swap occurred
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                        // If no swaps occurred during this pass, the array is already sorted
                                                                                                                                                                                                                                                                    if (!swapped) {
                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                // Helper method to print the array
                                                                                                                                                                                                                                                                                                                    public static void printArray(int[] arr) {
                                                                                                                                                                                                                                                                                                                            for (int num : arr) {
                                                                                                                                                                                                                                                                                                                                        System.out.print(num + " ");
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        System.out.println();
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                // Main method to test Bubble Sort
                                                                                                                                                                                                                                                                                                                                                                    public static void main(String[] args) {
                                                                                                                                                                                                                                                                                                                                                                            Scanner scanner = new Scanner(System.in);

                                                                                                                                                                                                                                                                                                                                                                                    // Prompt user for input
                                                                                                                                                                                                                                                                                                                                                                                            System.out.print("Enter the number of elements: ");
                                                                                                                                                                                                                                                                                                                                                                                                    int n = scanner.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                            int[] arr = new int[n];

                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Enter the elements:");
                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        arr[i] = scanner.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Original Array:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                printArray(arr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bubbleSort(arr); // Perform Bubble Sort

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Sorted Array:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printArray(arr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    