import java.util.Scanner;

public class MergeSort { 
    // Method to perform Merge Sort
        public static void mergeSort(int[] array, int left, int right) { 
                if (left < right) { 
                            int mid = left + (right - left) / 2; 
                                        
                                                    // Recursively sort first and second halves
                                                                mergeSort(array, left, mid); 
                                                                            mergeSort(array, mid + 1, right); 
                                                                                        
                                                                                                    // Merge the sorted halves
                                                                                                                merge(array, left, mid, right); 
                                                                                                                        } 
                                                                                                                            } 

                                                                                                                                // Method to merge two subarrays
                                                                                                                                    public static void merge(int[] array, int left, int mid, int right) { 
                                                                                                                                            int n1 = mid - left + 1; 
                                                                                                                                                    int n2 = right - mid; 
                                                                                                                                                            
                                                                                                                                                                    // Temporary arrays
                                                                                                                                                                            int[] L = new int[n1]; 
                                                                                                                                                                                    int[] R = new int[n2]; 
                                                                                                                                                                                            
                                                                                                                                                                                                    // Copy data to temp arrays
                                                                                                                                                                                                            for (int i = 0; i < n1; i++) 
                                                                                                                                                                                                                        L[i] = array[left + i]; 
                                                                                                                                                                                                                                for (int j = 0; j < n2; j++) 
                                                                                                                                                                                                                                            R[j] = array[mid + 1 + j]; 
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            // Merge the temp arrays back into the original array
                                                                                                                                                                                                                                                                    int i = 0, j = 0, k = left; 
                                                                                                                                                                                                                                                                            while (i < n1 && j < n2) { 
                                                                                                                                                                                                                                                                                        if (L[i] <= R[j]) { 
                                                                                                                                                                                                                                                                                                        array[k] = L[i]; 
                                                                                                                                                                                                                                                                                                                        i++; 
                                                                                                                                                                                                                                                                                                                                    } else { 
                                                                                                                                                                                                                                                                                                                                                    array[k] = R[j]; 
                                                                                                                                                                                                                                                                                                                                                                    j++; 
                                                                                                                                                                                                                                                                                                                                                                                } 
                                                                                                                                                                                                                                                                                                                                                                                            k++; 
                                                                                                                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                    // Copy remaining elements of L[], if any
                                                                                                                                                                                                                                                                                                                                                                                                                            while (i < n1) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                        array[k] = L[i]; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                    i++; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                k++; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Copy remaining elements of R[], if any
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (j < n2) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            array[k] = R[j]; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        j++; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    k++; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Method to print the array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static void printArray(int[] array) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int num : array) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print(num + " "); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println(); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Main method to test Merge Sort
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static void main(String[] args) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Scanner scanner = new Scanner(System.in);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Prompt user for input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.print("Enter the number of elements: "); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int n = scanner.nextInt(); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int[] array = new int[n]; 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Enter the elements:"); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < n; i++) { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            array[i] = scanner.nextInt(); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Original Array:"); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printArray(array); 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mergeSort(array, 0, array.length - 1); // Perform Merge Sort

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Sorted Array:"); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printArray(array); 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        