import java.util.Scanner;

public class QuickSort {

    // Method to perform Quick Sort
        public static void quickSort(int[] arr, int low, int high) {
                if (low < high) {
                            int pivotIndex = partition(arr, low, high);

                                        // Recursively sort elements before and after partition
                                                    quickSort(arr, low, pivotIndex - 1);
                                                                quickSort(arr, pivotIndex + 1, high);
                                                                        }
                                                                            }

                                                                                // Partition method
                                                                                    public static int partition(int[] arr, int low, int high) {
                                                                                            int pivot = arr[high]; // Pivot element
                                                                                                    int i = low - 1; // Index of smaller element

                                                                                                            for (int j = low; j < high; j++) {
                                                                                                                        if (arr[j] <= pivot) {
                                                                                                                                        i++;
                                                                                                                                                        // Swap arr[i] and arr[j]
                                                                                                                                                                        int temp = arr[i];
                                                                                                                                                                                        arr[i] = arr[j];
                                                                                                                                                                                                        arr[j] = temp;
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                    // Swap arr[i + 1] and pivot (arr[high])
                                                                                                                                                                                                                                            int temp = arr[i + 1];
                                                                                                                                                                                                                                                    arr[i + 1] = arr[high];
                                                                                                                                                                                                                                                            arr[high] = temp;

                                                                                                                                                                                                                                                                    return i + 1; // Return the partition index
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                            // Method to print the array
                                                                                                                                                                                                                                                                                public static void printArray(int[] arr) {
                                                                                                                                                                                                                                                                                        for (int num : arr) {
                                                                                                                                                                                                                                                                                                    System.out.print(num + " ");
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    System.out.println();
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            // Main method to test Quick Sort
                                                                                                                                                                                                                                                                                                                                public static void main(String[] args) {
                                                                                                                                                                                                                                                                                                                                        Scanner scanner = new Scanner(System.in);

                                                                                                                                                                                                                                                                                                                                                // Prompt user for input
                                                                                                                                                                                                                                                                                                                                                        System.out.print("Enter the number of elements: ");
                                                                                                                                                                                                                                                                                                                                                                int n = scanner.nextInt();
                                                                                                                                                                                                                                                                                                                                                                        int[] arr = new int[n];

                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Enter the elements:");
                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                    arr[i] = scanner.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Original Array:");
                                                                                                                                                                                                                                                                                                                                                                                                                            printArray(arr);

                                                                                                                                                                                                                                                                                                                                                                                                                                    quickSort(arr, 0, arr.length - 1); // Perform Quick Sort

                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Sorted Array:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                    printArray(arr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                            scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                